# Generated by Django 5.1.1 on 2024-09-29 21:28

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_task_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='api.unit'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.UploadToPathAndRename('comment')),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.UploadToPathAndRename('volunteer')),
        ),
    ]
