# Generated by Django 5.1.1 on 2024-09-30 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_unit_description_unit_title_volunteer_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='unit',
        ),
        migrations.AddField(
            model_name='link',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.unit'),
            preserve_default=False,
        ),
    ]
